version: "3.3"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    # volumes:
    #   - ./bitnami/zookeeper:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9101:9101"
    # expose:
    #   - "9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    # volumes:
    #   - ./bitnami/kafka:/bitnami/kafka

    # kafdrop:
    #   image: obsidiandynamics/kafdrop
    #   container_name: kafdrop
    #   ports:
    #     - "9000:9000"
    #   environment:
    #     KAFKA_BROKERCONNECT: "kafka:9092"
    #     JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:=UseStringDeduplication -noverify"
    #   depends_on:
    #     - kafka

    # k6:
    #   image: grafana/k6:latest
    #   # networks:
    #   #   - k6
    #   ports:
    #     - "6565:6565"
    #     # environment:
    #     # - K6_OUT=influxdb=http://influxdb:8086/k6
    #   volumes:
    #     - ./tests:/scripts
  k6:
    image: loadimpact/k6
    container_name: k6
    # environment:
    #   - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts
